# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marshl < Formula
  desc "marshl — local agent supervisor that bridges to the Marshl cloud."
  homepage "https://marshl.run"
  version "0.0.1-rc3"
  license "Proprietary"

  on_macos do
    url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.0.1-rc3/marshl_0.0.1-rc3_darwin_all.tar.gz"
    sha256 "6d95c9385ed4cc63b96aab477796a05857c45d28f4e923d0594f9a584f12504d"

    define_method(:install) do
      bin.install "marshl"
      bin.install "marshld"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.0.1-rc3/marshl_0.0.1-rc3_linux_amd64.tar.gz"
      sha256 "ed4ba929c94b44b68cab680e5d7e73eebe220067255cae393415632573867a95"
      define_method(:install) do
        bin.install "marshl"
        bin.install "marshld"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.0.1-rc3/marshl_0.0.1-rc3_linux_arm64.tar.gz"
      sha256 "5490299a96a4d58d117126fe26b6b4c895f287a82c13bc1a09ac319f47856a86"
      define_method(:install) do
        bin.install "marshl"
        bin.install "marshld"
      end
    end
  end

  def caveats
    <<~EOS
      Next steps:
        marshl install          # set up the marshld service
        marshl login            # authenticate
        marshl register .       # register the current folder
    EOS
  end

  test do
    system "#{bin}/marshl", "--version"
    system "#{bin}/marshld", "--version"
  end
end
