# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marshl < Formula
  desc "marshl — local agent supervisor that bridges to the Marshl cloud."
  homepage "https://marshl.run"
  version "0.1.1"
  license "Proprietary"

  on_macos do
    url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.1.1/marshl_0.1.1_darwin_all.tar.gz"
    sha256 "467b816b125888707b8aadb40dfc103ad731e5729026ccb35d31ec8c1b54cca6"

    define_method(:install) do
      bin.install "marshl"
      bin.install "marshld"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.1.1/marshl_0.1.1_linux_amd64.tar.gz"
      sha256 "9efc20e029218453647433a20c8088ecdedde8ed4be3634ae54bb9e2413c0e9c"
      define_method(:install) do
        bin.install "marshl"
        bin.install "marshld"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.1.1/marshl_0.1.1_linux_arm64.tar.gz"
      sha256 "ebee00471901e4713042f805c32c7e857e9df453dd722d78243bebfa5b14ffac"
      define_method(:install) do
        bin.install "marshl"
        bin.install "marshld"
      end
    end
  end

  def caveats
    <<~EOS
      Next steps:
        marshl install          # set up the marshld service
        marshl login            # authenticate
        marshl register .       # register the current folder
    EOS
  end

  test do
    system "#{bin}/marshl", "--version"
    system "#{bin}/marshld", "--version"
  end
end
