# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marshl < Formula
  desc "marshl — local agent supervisor that bridges to the Marshl cloud."
  homepage "https://marshl.run"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.1.0/marshl_0.1.0_darwin_all.tar.gz"
    sha256 "a47280db5632c569872ff67242baa090d3fcffe5886e769f2bffff6f05556a55"

    define_method(:install) do
      bin.install "marshl"
      bin.install "marshld"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.1.0/marshl_0.1.0_linux_amd64.tar.gz"
      sha256 "3ca459c1a39c138746334b31e82d668fea6caf7268f75b017cbbcdb9f71d7b6f"
      define_method(:install) do
        bin.install "marshl"
        bin.install "marshld"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KultivatorConsulting/marshl/releases/download/v0.1.0/marshl_0.1.0_linux_arm64.tar.gz"
      sha256 "f033b86a3a5f7a57e89825f4c617c5500d804adbe8808a0272325ee46eb60a3e"
      define_method(:install) do
        bin.install "marshl"
        bin.install "marshld"
      end
    end
  end

  def caveats
    <<~EOS
      Next steps:
        marshl install          # set up the marshld service
        marshl login            # authenticate
        marshl register .       # register the current folder
    EOS
  end

  test do
    system "#{bin}/marshl", "--version"
    system "#{bin}/marshld", "--version"
  end
end
